# Generated by Django 3.1.1 on 2020-09-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.SmallIntegerField(default=0)),
                ('xname', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_no', models.SmallIntegerField(default=0)),
                ('xname', models.CharField(default='', max_length=64)),
                ('add1', models.CharField(default='', max_length=32)),
                ('add2', models.CharField(default='', max_length=32)),
                ('add3', models.CharField(default='', max_length=32)),
                ('add4', models.CharField(default='', max_length=32)),
                ('mobile', models.CharField(default='', max_length=11)),
                ('pan', models.CharField(default='', max_length=32)),
                ('wef', models.DateField(default='0100-01-01')),
                ('active', models.BooleanField(default=True)),
                ('remarks', models.CharField(default='', max_length=64)),
                ('uid', models.CharField(default='', max_length=5)),
                ('upwd', models.CharField(default='', max_length=64)),
                ('tran_next_id', models.BigIntegerField(default=0)),
                ('_userdet', models.SmallIntegerField(default=0)),
                ('auth_userdet', models.SmallIntegerField(default=0)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.contractor')),
                ('route_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.route')),
            ],
        ),
    ]
