# Generated by Django 3.1.1 on 2020-09-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='_userdet',
        ),
        migrations.RemoveField(
            model_name='booth',
            name='auth_userdet',
        ),
    ]
