# Generated by Django 3.1.1 on 2020-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20200927_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xname', models.CharField(default='', max_length=32)),
                ('itype', models.CharField(default='', max_length=1)),
            ],
        ),
    ]
