# Generated by Django 3.1.1 on 2020-09-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_itemmst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_from', models.SmallIntegerField(default=0)),
                ('t_upto', models.SmallIntegerField(default=0)),
                ('shift', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xdatetime', models.DateTimeField(default='0100-01-01 00:00:00')),
                ('xdate', models.DateField(default='0100-01-01')),
                ('booth_name', models.CharField(default='', max_length=64)),
                ('booth_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.contractor')),
                ('route_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.route')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.shift')),
            ],
        ),
        migrations.CreateModel(
            name='TranDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xdate', models.DateField(default='0100-01-01')),
                ('sno', models.SmallIntegerField(default=0)),
                ('shortname', models.CharField(default='', max_length=8)),
                ('unit', models.CharField(default='', max_length=8)),
                ('packingtype', models.CharField(default='', max_length=8)),
                ('sale_unit', models.CharField(default='', max_length=8)),
                ('quantity', models.SmallIntegerField(default=0)),
                ('booth_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.itemmst')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.shift')),
                ('tran_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.tran')),
            ],
            options={
                'db_table': 'trandet',
            },
        ),
    ]
