# Generated by Django 3.1.1 on 2020-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_auto_20200927_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='shift',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='trandet',
            name='shift',
            field=models.CharField(max_length=1),
        ),
    ]
