# Generated by Django 3.1.1 on 2020-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0008_auto_20200927_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
