# Generated by Django 3.1.1 on 2020-10-03 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0010_auto_20201003_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='contractor_id',
            field=models.ForeignKey(db_column='contractor_id', default='0', on_delete=django.db.models.deletion.CASCADE, to='booth.contractor'),
        ),
    ]
